### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by linxuan74** [colineRamee/UTM_simulator#1]
hi,I'm sorry to bother you, but I really have a problem that I can't solve by myself.
When I use 'python setup.py install' to install,it always shows the same error:(I posted a screenshot below)
![image](https://user-images.githubusercontent.com/108520099/187699843-21909630-8db2-4c11-a435-4339271dfad6.png)

**Comment by colineRamee** [comment]
In the setup.py try replacing gurobi by gurobipy

**Comment by linxuan74** [comment]
> Thank you very much.! With your help, I have solved this problem.
